// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://prvtymoorqzdmnckjdng.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBydnR5bW9vcnF6ZG1uY2tqZG5nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NDQ2MTgsImV4cCI6MjA4ODIyMDYxOH0.7-9BdxnbDbcGnx6iDl-gB9YPNM0nEOqfvnPYfzqRaAM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});